name: CICache

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vcpkg binary artifacts
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg-cache
          key: vcpkg-cache-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-cache-${{ runner.os }}-

      - name: Set vcpkg binary source env
        shell: bash
        run: echo "VCPKG_BINARY_SOURCES=clear;files,$GITHUB_WORKSPACE/vcpkg-cache,readwrite" >> $GITHUB_ENV

      - name: Clone vcpkg
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git checkout e140b1fde236eb682b0d47f905e65008a191800f

      - name: Bootstrap vcpkg
        shell: bash
        run: |
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Configure CMake with vcpkg
        shell: bash
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$(cygpath -u "$GITHUB_WORKSPACE")/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        shell: bash
        run: cmake --build build --config Release
