name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest # or ubuntu-latest, macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone vcpkg
          run: |
           git clone https://github.com/microsoft/vcpkg.git
           cd vcpkg
           git checkout e140b1fde236eb682b0d47f905e65008a191800f

      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        run: .\vcpkg\vcpkg.exe install --x-install-root=${{ github.workspace }}\vcpkg_installed

      # Build and run
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release
